package services;
// Generated Feb 25, 2016 9:15:53 PM by Hibernate Tools 4.3.1


/**
 * Accounts generated by
 */
public class Accounts implements java.io.Serializable {

    private Integer id;
    private String no;
    private String name;
    private String type;
    private BeginningBalances beginningBalances;
    //private Set AccountMap;

    public Accounts() {
    }

    public Accounts(String no, String name, String type) {
        this.no = no;
        this.name = name;
        this.type = type;
        //this.AccountMap = AccountMap;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNo() {
        return this.no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }
    
    public BeginningBalances getBeginningBalances() {
        return beginningBalances;
    }

    public void setBeginningBalances(BeginningBalances beginningBalances) {
        this.beginningBalances = beginningBalances;
    }

    /*public Set getAccountMap() {
        return AccountMap;
    }
    public void setAccountMap(Set AccountMap) {
        this.AccountMap = AccountMap;
    }*/
}
