package services;
// Generated Feb 25, 2016 9:15:53 PM by Hibernate Tools 4.3.1

/**
 * Accounts generated by
 */
public class BeginningBalances implements java.io.Serializable {

    private Integer accountId;
    private String year;
    private Double debet;
    private Double credit;
    private Accounts accounts;

    public BeginningBalances() {
    }

    public BeginningBalances(Integer accountId, String year, Double debet, Double credit) {
        this.accountId = accountId;
        this.year = year;
        this.debet = debet;
        this.credit = credit;
    }
    
    public Integer getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public Double getDebet() {
        return this.debet;
    }

    public void setDebet(Double debet) {
        this.debet = debet;
    }

    public Double getCredit() {
        return this.credit;
    }

    public void setCredit(Double credit) {
        this.credit = credit;
    }

    public Accounts getAccounts() {
        return accounts;
    }

    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
}
