package services;
// Generated Feb 25, 2016 9:15:53 PM by Hibernate Tools 4.3.1

/**
 * Accounts generated by
 */
public class BeginningBalances implements java.io.Serializable {
    private Integer id;
    private Integer accountId;
    private String accountNo;
    private String year;
    private Double debet = null;
    private Double credit = null;
    

    public BeginningBalances() {
    }

    public BeginningBalances(Integer accountId,String accountNo, String year, Double debet, Double credit) {
        this.accountId = accountId;
        this.accountNo = accountNo;
        this.year = year;
        this.debet = debet;
        this.credit = credit;
    }
    
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    public Integer getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    
    public String getAccountNo() {
        return this.accountNo;
    }

    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public Double getDebet() {
        return this.debet;
    }

    public void setDebet(Double debet) {
        this.debet = debet;
    }

    public Double getCredit() {
        return this.credit;
    }

    public void setCredit(Double credit) {
        this.credit = credit;
    }
   
}
