package services;
// Generated Feb 25, 2016 9:15:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;

/**
 * Journals generated by hbm2java
 */
public class Journals implements java.io.Serializable {

    private Integer id;
    private String number;
    private Date date;
    private String description;
    private String type;
    private String checkNumber;
    private Double debet;
    private Double credit;
    //private Set<JournalDetails> jd;
    

    public Journals() {
        
    }

    public Journals(String number, Date date, String description, String type, String checkNumber, Double debet, Double credit) {
        this.number = number;
        this.date = date;
        this.description = description;
        this.type = type;
        this.checkNumber = checkNumber;
        this.debet = debet;
        this.credit = credit;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCheckNumber() {
        return this.checkNumber;
    }

    public void setCheckNumber(String checkNumber) {
        this.checkNumber = checkNumber;
    }

    public Double getDebet() {
        return this.debet;
    }

    public void setDebet(Double debet) {
        this.debet = debet;
    }

    public Double getCredit() {
        return this.credit;
    }

    public void setCredit(Double credit) {
        this.credit = credit;
    }
    
    /*public Set getJd() {
        return this.jd;
    }
    
    public void setJd(Set jd) {
        this.jd = jd;
    }*/
}
