/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package services;
/**
 * TplProfit generated by hbm2java
 */

public class TplProfitLoss implements java.io.Serializable {
    private Integer id;
    private String description;
    
    public TplProfitLoss() {
    }
    
    public TplProfitLoss(String description) {
        this.description = description;
    }
    
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
