/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package services;
/**
 * TplProfit generated by hbm2java
 */

public class TrialBalances implements java.io.Serializable {
    private Integer id;
    private Double beginningBalanceDebet;
    private Double beginningBalanceCredit;
    private Double profitLossDebet;
    private Double profitLossCredit;
    private Double endingBalanceDebet;
    private Double endingBalanceCredit;
    
    
    public TrialBalances() {
    }
    
    public TrialBalances(Double beginningBalanceDebet,Double beginningBalanceCredit,Double profitLossDebet,Double profitLossCredit,Double endingBalanceDebet,Double endingBalanceCredit) {
        this.beginningBalanceDebet = beginningBalanceDebet;
        this.beginningBalanceCredit = beginningBalanceCredit;
        this.profitLossDebet = profitLossDebet;
        this.profitLossCredit = profitLossCredit;
        this.endingBalanceDebet = endingBalanceDebet;
        this.endingBalanceCredit = endingBalanceCredit;
    }
    
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    
    public Double getBeginningBalanceDebet() {
        return this.beginningBalanceDebet;
    }

    public void setBeginningBalanceDebet(Double beginningBalanceDebet) {
        this.beginningBalanceDebet = beginningBalanceDebet;
    }
    
    public Double getBeginningBalanceCredit() {
        return this.beginningBalanceCredit;
    }

    public void setBeginningBalanceCredit(Double beginningBalanceCredit) {
        this.beginningBalanceCredit = beginningBalanceCredit;
    }
    
    public Double getProfitLossDebet() {
        return this.profitLossDebet;
    }

    public void setProfitLossDebet(Double profitLossDebet) {
        this.profitLossDebet = profitLossDebet;
    }
    
    public Double getProfitLossCredit() {
        return this.profitLossCredit;
    }

    public void setProfitLossCredit(Double profitLossCredit) {
        this.profitLossCredit = profitLossCredit;
    }
    
    public Double getEndingBalanceDebet() {
        return this.endingBalanceDebet;
    }

    public void setEndingBalanceDebet(Double endingBalanceDebet) {
        this.endingBalanceDebet = endingBalanceDebet;
    }
    
    public Double getEndingBalanceCredit() {
        return this.endingBalanceCredit;
    }

    public void setEndingBalanceCredit(Double endingBalanceCredit) {
        this.endingBalanceCredit = endingBalanceCredit;
    }
}
