package services;
// Generated Feb 25, 2016 9:15:53 PM by Hibernate Tools 4.3.1

/**
 * Accounts generated by
 */
public class TrialBalances implements java.io.Serializable {

    private Integer id;
    private String accountNo;
    private String accountName;
    private Double beginningBalanceDebet;
    private Double beginningBalanceCredit;
    private Double profitLossDebet;
    private Double profitLossCredit;
    private Double balanceDebet;
    private Double balanceCredit;
    private Double endingBalanceDebet;
    private Double endingBalanceCredit;

    public TrialBalances() {
    }

    public TrialBalances(String accountNo, String accountName, Double beginningBalanceDebet, Double beginningBalanceCredit,Double balanceDebet,Double balanceCredit,Double endingBalanceDebet, Double endingBalanceCredit) {
        this.accountNo = accountNo;
        this.accountName = accountName;
        this.beginningBalanceDebet = beginningBalanceDebet;
        this.beginningBalanceCredit = beginningBalanceCredit;
        this.balanceDebet = balanceDebet;
        this.balanceCredit = balanceCredit;
        this.endingBalanceDebet = endingBalanceDebet;
        this.endingBalanceCredit = endingBalanceCredit;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAccountNo() {
        return this.accountNo;
    }

    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public Double getBeginningBalanceDebet() {
        return this.beginningBalanceDebet;
    }

    public void setBeginningBalanceDebet(Double beginningBalanceDebet) {
        this.beginningBalanceDebet = beginningBalanceDebet;
    }

    public Double getBeginningBalanceCredit() {
        return this.beginningBalanceCredit;
    }

    public void setBeginningBalanceCredit(Double beginningBalanceCredit) {
        this.beginningBalanceCredit = beginningBalanceCredit;
    }

    public Double getProfitLossDebet() {
        return this.profitLossDebet;
    }

    public void setProfitLossDebet(Double profitLossDebet) {
        this.profitLossDebet = profitLossDebet;
    }

    public Double getProfitLossCredit() {
        return this.profitLossCredit;
    }

    public void setProfitLossCredit(Double profitLossCredit) {
        this.profitLossCredit = profitLossCredit;
    }
    
    public Double getBalanceDebet() {
        return this.balanceDebet;
    }

    public void setBalanceDebet(Double balanceDebet) {
        this.balanceDebet = balanceDebet;
    }

    public Double getBalanceCredit() {
        return this.balanceCredit;
    }

    public void setBalanceCredit(Double balanceCredit) {
        this.balanceCredit = balanceCredit;
    }
    
    public Double getEndingBalanceDebet() {
        return this.endingBalanceDebet;
    }

    public void setEndingBalanceDebet(Double endingBalanceDebet) {
        this.endingBalanceDebet = endingBalanceDebet;
    }

    public Double getEndingBalanceCredit() {
        return this.endingBalanceCredit;
    }

    public void setEndingBalanceCredit(Double endingBalanceCredit) {
        this.endingBalanceCredit = endingBalanceCredit;
    }

}
