/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gl.journal;

import com.mxrck.autocompleter.TextAutoCompleter;
import gl.accounts.CoaShared;
import helpers.Format;
import helpers.Lang;
import helpers.Validator.IsValidValidator;
import helpers.Validator.RequiredValidator;
import java.util.Iterator;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JTable;
import models.Account;
import models.JournalDetail;
import services.Accounts;

/**
 *
 * @author BDO-IT
 */
public class TransactionForm extends javax.swing.JDialog {

    public Transaction list = new Transaction();
    public JTable table;
    public Integer row;
    JournalDetail model;
    private String accountNo;
    
    public String getAccountNo(){
        return accountNo;
    }
    
    public void setAccountNo(String var) {
        accountNo = var;
    }
    
    /**
     * Creates new form TransactionForm
     *
     * @param parent
     * @param modal
     */
    public TransactionForm(JInternalFrame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        initForm();
    }
    
    private void initForm() {
        model = new JournalDetail();
        if (model.getIsEdit() != true) {
            jTextFieldAccountNo.setText("");
            jTextFieldDescription.setText("");
            jTextFieldDebet.setText("0.00");
            jTextFieldCredit.setText("0.00");
            jButtonAdd.setText(Lang.getString("App.add"));
        }else {
            jTextFieldAccountNo.setText(model.getAccountNo_());
            jTextFieldDescription.setText(model.getDescription_());
            jTextFieldDebet.setText(Format.currency(model.getDebet_(),2));
            jTextFieldCredit.setText(Format.currency(model.getCredit_(),2));
            jButtonAdd.setText(Lang.getString("App.update"));
        }
        
    }
    
    public void getItemSelected(String no) {
        jTextFieldAccountNo.setText(no);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAccountNo = new javax.swing.JLabel();
        jTextFieldAccountNo = new javax.swing.JTextField();
        jLabelAccountName = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jLabelDebet = new javax.swing.JLabel();
        jTextFieldDebet = new javax.swing.JTextField();
        jLabelCredit = new javax.swing.JLabel();
        jTextFieldCredit = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonSearchAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("TransactionForm"); // NOI18N

        jLabelAccountNo.setText("Account No");

        jTextFieldAccountNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAccountNoKeyTyped(evt);
            }
        });

        jLabelAccountName.setText("Description");

        jLabelDebet.setText("Debet");

        jTextFieldDebet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDebetFocusLost(evt);
            }
        });
        jTextFieldDebet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDebetKeyTyped(evt);
            }
        });

        jLabelCredit.setText("Credit");

        jTextFieldCredit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCreditFocusLost(evt);
            }
        });
        jTextFieldCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCreditKeyTyped(evt);
            }
        });

        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/plus_16X16.png"))); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/cancel_16X16.png"))); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSearchAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/search_16x16.png"))); // NOI18N
        jButtonSearchAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAccountName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAccountNo, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearchAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDebet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDebet, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAccountNo)
                    .addComponent(jTextFieldAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchAccount))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAccountName)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDebet)
                    .addComponent(jTextFieldDebet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCredit)
                    .addComponent(jTextFieldCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        Account accountModel = new Account();
        RequiredValidator accountNoVal = new RequiredValidator(this, jTextFieldAccountNo, "The field account no is required !");
        IsValidValidator isExists = new IsValidValidator(this, jTextFieldAccountNo, "The field account no is no exists !",accountModel.isExists(jTextFieldAccountNo.getText()));
        RequiredValidator descriptionVal = new RequiredValidator(this, jTextFieldDescription, "The field description is required !");
        RequiredValidator debetVal = new RequiredValidator(this, jTextFieldDebet, "The field debet is required !");
        RequiredValidator creditVal = new RequiredValidator(this, jTextFieldCredit, "The field credit name is required !");

        if ((accountNoVal.verify(jTextFieldAccountNo)) && (isExists.verify(jTextFieldAccountNo) ) && (descriptionVal.verify(jTextFieldDescription)) && (debetVal.verify(jTextFieldDebet)) && (creditVal.verify(jTextFieldCredit))) {
            String xaccountNo = jTextFieldAccountNo.getText();
            String xdescription = jTextFieldDescription.getText();
            Double xdebet = Format.stringToDouble(jTextFieldDebet.getText());
            Double xcredit = Format.stringToDouble(jTextFieldCredit.getText());
            model = new JournalDetail();
            if(model.getIsEdit() ==  false) {
                model.setPos(table.getRowCount() + 1);
                model.setAccountNo(xaccountNo);
                model.setDescription(xdescription);
                model.setDebet(xdebet);
                model.setCredit(xcredit);
                model.addTableRow(table);
            } else {
                table.setValueAt(jTextFieldAccountNo.getText(),row, 1);
                table.setValueAt(jTextFieldDescription.getText(),row, 2);
                table.setValueAt(jTextFieldDebet.getText(),row, 3);
                table.setValueAt(jTextFieldCredit.getText(),row, 4);
            }
            list.initCalculation();
            this.dispose();
        }


    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSearchAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAccountActionPerformed
        // TODO add your handling code here:
        CoaShared shared = new CoaShared(this,false);
        shared.setLocationRelativeTo(this);
        shared.pack();
        shared.transactionForm = this;
        shared.formName = this.getName();
        shared.setVisible(true);
    }//GEN-LAST:event_jButtonSearchAccountActionPerformed

    private void jTextFieldDebetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDebetKeyTyped
        // TODO add your handling code here:
        Format.isDecimal(evt);
        
    }//GEN-LAST:event_jTextFieldDebetKeyTyped

    private void jTextFieldCreditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCreditKeyTyped
        // TODO add your handling code here:
        Format.isDecimal(evt);
    }//GEN-LAST:event_jTextFieldCreditKeyTyped

    private void jTextFieldAccountNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccountNoKeyTyped
        // TODO add your handling code here:
        TextAutoCompleter autoComplete;
        autoComplete = new TextAutoCompleter(jTextFieldAccountNo) {
            @Override
            protected void acceptedListItem(Object o) {
                if (o == null) {
                    return;
                }

                String str;
                Account model = new Account();
                Accounts  acc = model.getRowByAccountName(o.toString());
                if(acc != null) 
                    str = acc.getNo();
                else str = "0";
                this.getTextComponent().setText(str);
            }

        };

        String result = jTextFieldAccountNo.getText();
        if (result.length() > 0) {
            Account accountModel = new Account();
            List listed = accountModel.getRowsByList();
            for (Iterator iterator = listed.iterator(); iterator.hasNext();) {
                Accounts acc = (Accounts) iterator.next();
                autoComplete.addItem(acc.getNo() + " " + acc.getName() );
            }
        }
    }//GEN-LAST:event_jTextFieldAccountNoKeyTyped

    private void jTextFieldDebetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDebetFocusLost
        // TODO add your handling code here:
        if(jTextFieldDebet.getText().length() > 0 ){
            jTextFieldDebet.setText(Format.currency(Format.stringToDouble(jTextFieldDebet.getText()),2));
        }
    }//GEN-LAST:event_jTextFieldDebetFocusLost

    private void jTextFieldCreditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCreditFocusLost
        // TODO add your handling code here:
        if(jTextFieldCredit.getText().length() > 0 ){
            jTextFieldCredit.setText(Format.currency(Format.stringToDouble(jTextFieldCredit.getText()),2));
        }
    }//GEN-LAST:event_jTextFieldCreditFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TransactionForm dialog = new TransactionForm(new JInternalFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSearchAccount;
    private javax.swing.JLabel jLabelAccountName;
    private javax.swing.JLabel jLabelAccountNo;
    private javax.swing.JLabel jLabelCredit;
    private javax.swing.JLabel jLabelDebet;
    private javax.swing.JTextField jTextFieldAccountNo;
    private javax.swing.JTextField jTextFieldCredit;
    private javax.swing.JTextField jTextFieldDebet;
    private javax.swing.JTextField jTextFieldDescription;
    // End of variables declaration//GEN-END:variables
}
